import { SET_CITY } from '../actions';
 
// CREAR REDUCER PARA UNA SOLA ACCION. FUNCION PURA, SOLO DEPENDE DE LOS PARAMETROS DE ENTRADA,
// NO DEPENDE DE UNA BASE DE DATOS, SOLO DE LO QUE LE DAMOS NOSOTROS. 
// NO HAY QUE ALTERAR VALORES QUE VIENEN COMO PARAMETROS
//NO HAY QUE HACER state.prop = 'nuevo valor' XXXXXXXXXXXXXXXXXX
// HACER UNA COPIA CON EL SPREAD OPERATOR (...state) Y GENERAR UN OBJETO CON LA PROP MODIF.


// HACIENDO UN STATE = {} LE DAMOS UN VALOR DEFAULT AL STATE

//SWITCH : CUANDO UN ACTION TENGA UN TYPE IGUAL A CITY VAMOS A MODIF EL ESTADO.

// ...STATE = ESTADO ANTERIOR DEL STATE
// PAYLOAD (NOMBRE CONVENCIONAL) = VALUE

export const city = (state ={}, action) => {
    switch (action.type) {
        case SET_CITY:
            return action.payload;    
        default:
            return state;
    }
}